uploads = []
generated = []

[[outputs]]
id = "MB1vG7hts8NQ6qkVXv-DJ"
uri = "file://prolongation_report.xlsx"
type = "table"
title = "Отчёт по пролонгациям (Excel)"

[[outputs]]
id = "MPNp17dvxuXBbWoTPwW0P"
uri = "file://prolongation_chart.png"
type = "image"
title = "График коэффициентов пролонгации"

[[outputs]]
id = "dnH2MN4A9mpQJo4eTyBFI"
uri = "file://prolongation_analysis.py"
type = "unspecified"
title = "Код анализа пролонгаций"
